package:
  name: deepsvr
  version: "0.1.0"

source:
  url: https://github.com/griffithlab/DeepSVR/releases/download/v0.1.0/deepsvr-0.1.0.tar.gz
  sha256: b95763c9fdfc718938ecf537a94714e2b4cbb1f083859faa7c86c2d90d22ef01 

build:                                                                          
  noarch: python                                                                
  script: 
    - flake8 . -v --config=.flake8rc
    - nosetests --verbose
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir .
  number: 0
  entry_points:
    - deepsvr = deepsvr.cli:main

requirements:
  build:
    - python
    - setuptools
    - nose
    - flake8
    - pandas
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
    - bam-readcount
    - convert_zero_one_based
    - click
    - tensorflow
    - keras
    - h5py
  run:
    - python
    - bam-readcount
    - pandas
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
    - convert_zero_one_based
    - click
    - tensorflow
    - keras
    - scikit-learn
    - h5py

test:
  imports:
    - deepsvr
  commands:
    - deepsvr --version


about:
  home: https://github.com/griffithlab/deepsvr
  license: MIT
  summary: "DeepSVR stands for deep somatic variant refinement. It uses deep learning to classify real somatic and anomalous variants in paired tumor sequencing data."
