package:
  name: pdb2pqr
  version: "2.1.1"

source:
  url: https://github.com/Electrostatics/apbs-pdb2pqr/releases/download/pdb2pqr-2.1.1_release/pdb2pqr-src-2.1.1.tar.gz
  md5: 266dd7614de4adb0981d50471d38083a

build:
  skip: True  # [not py27]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - zlib
  run:
    - python
    - numpy
    - zlib

test:
  commands:
    - pdb2pqr --version

about:
  home: 'https://github.com/Electrostatics/apbs-pdb2pqr/tree/master/pdb2pqr'
  license: MIT
  summary: 'Prepare PDB structures for continuum solvation calculations'
  license_family: MIT
