package:
  name: mothur
  version: 1.40.5

source:
  url: https://github.com/mothur/mothur/archive/v1.40.5.tar.gz
  md5: d57847849fdb961c3f66c9b9fdf3057b
  patches:
    - patch
    - patch2

build:
  number: 0
  skip: True # [not linux64 or osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib
    - ncurses
    - readline
    - boost
    - blast-legacy
  run:
    - zlib
    - ncurses
    - readline
    - boost
    - blast-legacy
test:
  commands:
    - mothur "#help()"
    - uchime --version

about:
  home: http://www.mothur.org
  license: GPL
  license_file: LICENSE.md
  summary: This project seeks to develop a single piece of open-source, expandable software to fill the bioinformatics needs of the microbial ecology community.
